##############################################################################
#
# File: doxygen-gh-pages.yml
#
# Function:
#   Build Doxygen documentation and deploy to GitHub Pages.
#
##############################################################################

name: Doxygen Pages

on:
  push:
    branches: [master]

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Build Doxygen
        run: doxygen Doxyfile

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doxygen/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
